# Generated by Django 5.0.4 on 2024-12-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querys", "0001_initial"),
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="response", name="request_prompt",),
        migrations.RemoveField(model_name="response", name="user",),
        migrations.AddField(
            model_name="response",
            name="query_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="querys.query",
            ),
            preserve_default=False,
        ),
    ]
