# Generated by Django 5.0.4 on 2025-01-04 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "responses",
            "0002_remove_response_request_prompt_remove_response_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="response", old_name="query_id", new_name="query",
        ),
        migrations.RenameField(
            model_name="response", old_name="response", new_name="result",
        ),
        migrations.AddField(
            model_name="response",
            name="user",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
